{{- range $key, $val := .Values.apps }}
# THÊM DÒNG IF NÀY: Chỉ tạo Service nếu tên KHÔNG PHẢI là jenkins
{{- if ne $val.name "jenkins" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $val.name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ $val.port | default 80 }}
      protocol: TCP
  selector:
    app: {{ $val.name }}
---
{{- end }}
{{- end }}