server {
    listen 80; # Trong container nên dùng cổng 80 chuẩn
    server_name localhost;

    # 1. Phục vụ Frontend (Đường dẫn chuẩn trong Container Nginx)
    location / {
        root /usr/share/nginx/html; # Đây là nơi ta COPY code vào trong Dockerfile
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 2. Reverse Proxy sang Flask AI
;     location /api/ai/ {
;         # Trong K8s, ta dùng tên Service thay vì IP máy
;         proxy_pass http://flask-ai-service:5000/;
;         proxy_set_header Host $host;
;         proxy_set_header X-Real-IP $remote_addr;
;         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
;     }

    # 3. Reverse Proxy sang Node.js (Backend chính)
;     location /api/main/ {
;         proxy_pass http://node-main-service:3000/;
;         proxy_set_header Host $host;
;         proxy_set_header X-Real-IP $remote_addr;
;     }
}