server {
    listen 80; # Trong container nên dùng cổng 80 chuẩn
    server_name localhost;

    # 1. Phục vụ Frontend (Đường dẫn chuẩn trong Container Nginx)
    location / {
        root /usr/share/nginx/html; # Đây là nơi ta COPY code vào trong Dockerfile
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}