# Cấu hình chung cho các Service
apps:
  tech:
    name: dev-repo-web-tech
    image: devmindtan/dev-repo:web-tech-v1.0.71
    path: /web-tech
    port: 80
  user:
    name: dev-repo-web-user
    image: devmindtan/dev-repo:web-user-v1.0.71
    path: /web-user
    port: 80
  jenkins:
    name: jenkins
    port: 8080
    path: /jenkins

# Cấu hình Ingress tổng
ingress:
  host: laptop.devmindtan.uk